////////////////////////////////////////// Imports
import 'dotenv/config';
import express from "express";
//import dotenv from "dotenv";
import cors from 'cors';
import cookieParser from 'cookie-parser';
import path from 'path'; // logic: importing path to resolve the frontend dist directory
import helmet from 'helmet';

// Import tech advisor
import techAdvisorRoutes from './routes/techAdvisorRoutes.js';

///////// Import Logging Middleware
import { logReq } from "./middleware/logger.js";

///////// Import Error Handling Middleware
import { error404, globalErr } from './middleware/error.js';

///////// Import routes
import authRoutes from './routes/authRoutes.js';
import productRoutes from './routes/productRoutes.js';
import orderRoutes from './routes/orderRoutes.js';
import adminRoutes from './routes/adminRoutes.js';

//////// Import Database
import connectDB from './database/conn.js';

// load env vars from .env file
//dotenv.config();



////////////////////////////////////////// Setups
const app = express();
const PORT = process.env.PORT || 3001;
// connect database
connectDB();




//////////////////////////////////////// Middleware

// logic: deploying helmet to secure http headers and prevent xss/clickjacking.
// i am modifying the content security policy to explicitly allow my local ports, but blocking everything else.
app.use(helmet({
    contentSecurityPolicy: {
        directives: {
            defaultSrc: ["'self'"],
            scriptSrc: ["'self'", "'unsafe-inline'"],
            styleSrc: ["'self'", "'unsafe-inline'"],
            imgSrc: ["'self'", "data:", "https:"],
            // logic: strictly allowing only my express server and vite dev server
            connectSrc: ["'self'", "http://localhost:3000", "http://localhost:5173"],
        },
    },
    crossOriginEmbedderPolicy: false,
}));


// updating default cors configuration so it accepts credentials (cookies) across origins.
app.use(cors({ origin: true, credentials: true }));

app.use(express.json());
// parse incoming cookies
app.use(cookieParser());

// logging middleware
app.use(logReq);



//////////////////////////////////////// Routes

////////////TESTING
// app.get("/", (req, res) => {
//   res.send("testing read!");
// });
////////////TESTING

// adding the authentication router
app.use('/api/auth', authRoutes);
// adding the products router
app.use('/api/products', productRoutes);
// adding the orders router
app.use('/api/orders', orderRoutes);
// adding the admins router
app.use('/api/admin', adminRoutes);
// adding the tech advisor routes
app.use('/api/chat', techAdvisorRoutes);


// logic: production deployment configuration. dynamically resolving the path to the compiled react frontend.
const __dirname = path.resolve();

// if (process.env.NODE_ENV === 'production') {
//     // logic: pointing express to the dist folder generated by vite.
//     app.use(express.static(path.join(__dirname, '../Frontend/dist')));

//     // logic: catching any route that isn't an api endpoint and returning the react index.html so the client-side browser router can take over.
//     app.get(/(.*)/, (req, res) =>
//         res.sendFile(path.join(__dirname, '../Frontend', 'dist', 'index.html'))
//     );
// } else {
//     app.get('/', (req, res) => {
//         res.status(200).json({ message: "gadgetshack api is live in development mode." });
//     });
// }

app.get('/', (req, res) => {
    res.status(200).json({ message: "gadgetshack api is live in production mode." });
});

//////////////////////////////////////// Error Handling
app.use(error404);
app.use(globalErr);


////////////////////////////////////////// Listener
app.listen(PORT, () => {
    console.log(`Server running on PORT: ${PORT}`);
});